create table scope(
    id integer generated by default as identity,
    name varchar(255),
    groupid varchar(255),
    artifact_id varchar(255),
    primary key (id)
);

create table scope_version(
    id integer generated by default as identity,
    version varchar(255),
    released date,
    scope_id integer,
    primary key (id)
);

alter table scope_version
add constraint FKb70oijed6fsw8qwvgergcxg80
foreign key (scope_id) references scope;

insert into scope (name, groupid, artifact_id) values ('JPA', 'jakarta.persistence', 'jakarta.persistence-api');
insert into scope (name, groupid, artifact_id) values ('EclipseLink', 'org.eclipse.persistence', 'org.eclipse.persistence.jpa');

insert into scope_version (version, released, scope_id) VALUES ('3.1.0', '2022-04-01', 1);
insert into scope_version (version, released, scope_id) VALUES ('4.0.2', '2023-06-16', 2);
